### ISSUE TITLE
[Bug] Crafting Recipes with STAPI are broken

### ISSUE THREAD

**Issue by matthewperiut** [BetterThanUpdates/apron#45]
Craft anything while STAPI is installed, and it causes a crash, plus HMI doesn't display recipe.

I think the best solution is if possible, try to use STAPI recipe event to add recipes after adding to a recipe array.

**Comment by thecatcore** [comment]
Fixed by https://github.com/thecatcore/Apron/commit/e7c9bc8d81dd69ecc920596d59682a870164d4c3
