### ISSUE TITLE
[Bug] Crashes While Trying to Run on Ornithe

### ISSUE THREAD

**Issue by Cuteistfox** [BetterThanUpdates/apron#52]
**Affected mods:**
apron

## To Reproduce:
1. Install Apron and the affected mod
2. try to boot the game

## Expected behavior:
It boots

## Actual behavior:
Its crashes

## Version info:
 - Apron version: `1.7.3+build.1`
 - newest one

**Additional context**
on orthinite b1.7.3 quilt
[log](https://mclo.gs/QiRLWLR)

**Comment by thecatcore** [comment]
You are trying to run Ornithe and Babric mods together when they are incompatible with each other.

**Comment by Cuteistfox** [comment]
> You are trying to run Ornithe and Babric mods together when they are incompatible with each other.

oh. Also is this mod babric or ornithe?

**Comment by Cuteistfox** [comment]
also i wish modrinth will add "babric" and "ornithe" mod loader filters

**Comment by thecatcore** [comment]
It's a Babric mod
